import type { Exercise } from "./exercises";

export const EXTRA_EXERCISES: Record<string, Exercise[]> = {
  subjuntivo: [
    { sentence: "Es importante que ___ a tiempo.", options: ["llegues", "llegas", "llegarás", "llegaste"], answer: "llegues", explanation: "'Es importante que' → estructura impersonal de necesidad → subjuntivo.", type: "choice" },
    { sentence: "No pienso que ___ buena idea.", options: ["sea", "es", "será", "fue"], answer: "sea", explanation: "'No pensar que' expresa opinión negativa → subjuntivo.", type: "choice" },
    { sentence: "Antes de que ___, cierra la ventana.", options: ["llueva", "llueve", "lloverá", "llovió"], answer: "llueva", explanation: "'Antes de que' siempre va con subjuntivo.", type: "choice" },
    { sentence: "Te llamaré cuando ___ del trabajo.", answer: "salga", explanation: "'Cuando' + futuro → subjuntivo del verbo 'salir'.", type: "write" },
    { sentence: "Necesito que me ___ un favor.", answer: "hagas", explanation: "'Necesitar que' expresa petición → subjuntivo de 'hacer'.", type: "write" },
    { sentence: "Es probable que mañana ___.", options: ["nieve", "nieva", "nevará", "nevó"], answer: "nieve", explanation: "'Es probable que' expresa posibilidad → subjuntivo.", type: "choice" },
    { sentence: "Me da miedo que ___ sola de noche.", options: ["salga", "sale", "saldrá", "salió"], answer: "salga", explanation: "'Dar miedo que' expresa emoción → subjuntivo.", type: "choice" },
    { sentence: "No hay nadie que ___ eso.", options: ["sepa", "sabe", "sabrá", "supo"], answer: "sepa", explanation: "Antecedente negativo ('no hay nadie que') → subjuntivo.", type: "choice" },
  ],
  pasados: [
    { sentence: "Cuando ___ pequeño, ___ en el campo.", options: ["era, vivía", "fui, viví", "era, viví", "fui, vivía"], answer: "era, vivía", explanation: "Dos descripciones habituales del pasado → ambas en imperfecto.", type: "choice" },
    { sentence: "Ayer ___ un accidente en la autopista.", options: ["hubo", "había", "ha habido", "habrá"], answer: "hubo", explanation: "Evento puntual ayer → pretérito indefinido.", type: "choice" },
    { sentence: "Siempre ___ café por la mañana, pero ayer ___ té.", options: ["tomaba, tomé", "tomé, tomaba", "tomaba, tomaba", "tomé, tomé"], answer: "tomaba, tomé", explanation: "Hábito (imperfecto) + acción puntual que rompe el hábito (indefinido).", type: "choice" },
    { sentence: "El día que nos ___, ___ sol.", answer: "conocimos, hacía", explanation: "Evento puntual (indefinido) + descripción del tiempo (imperfecto).", type: "write" },
    { sentence: "Cuando ___ en la calle, ___ a llover.", answer: "estaba, empezó", explanation: "Acción en progreso (imperfecto) interrumpida por otra (indefinido).", type: "write" },
    { sentence: "De joven ___ mucho deporte.", options: ["hacía", "hizo", "ha hecho", "hará"], answer: "hacía", explanation: "'De joven' indica hábito pasado → imperfecto.", type: "choice" },
  ],
  "estaba-estuvo": [
    { sentence: "El agua ___ muy fría.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Descripción de un estado cuando lo experimentamos → imperfecto.", type: "choice" },
    { sentence: "___ esperándote una hora.", options: ["Estuve", "Estaba"], answer: "Estuve", explanation: "Duración definida completada ('una hora') → indefinido.", type: "choice" },
    { sentence: "La tienda ___ cerrada todo el fin de semana.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Período cerrado y completado ('todo el fin de semana') → indefinido.", type: "choice" },
    { sentence: "Cuando llegué, ella ya no ___ allí.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Estado encontrado al llegar → imperfecto.", type: "choice" },
    { sentence: "El concierto ___ increíble.", answer: "estuvo", explanation: "Valoración de un evento terminado → indefinido.", type: "write" },
    { sentence: "Mi madre ___ preocupada toda la noche.", answer: "estuvo", explanation: "Duración definida ('toda la noche') → indefinido.", type: "write" },
    { sentence: "¿Cómo ___ la película?", answer: "estuvo", explanation: "Valoración de algo ya terminado → indefinido.", type: "write" },
    { sentence: "No sé dónde ___ las llaves.", answer: "estaban", explanation: "Ubicación desconocida (estado) → imperfecto.", type: "write" },
  ],
  "ser-estar": [
    { sentence: "Juan ___ cansado después del trabajo.", options: ["está", "es"], answer: "está", explanation: "Estado temporal (resultado de algo) → estar.", type: "choice" },
    { sentence: "La reunión ___ a las tres.", options: ["es", "está"], answer: "es", explanation: "Hora de eventos → ser.", type: "choice" },
    { sentence: "___ claro que no vendrá.", options: ["Está", "Es"], answer: "Está", explanation: "'Estar claro' = resulta evidente (estado).", type: "choice" },
    { sentence: "Mi padre ___ profesor de historia.", answer: "es", explanation: "Profesión → ser.", type: "write" },
    { sentence: "La sopa ___ fría.", answer: "está", explanation: "Temperatura (estado temporal) → estar.", type: "write" },
    { sentence: "Carlos ___ muy alto para su edad.", options: ["es", "está"], answer: "es", explanation: "Característica física inherente → ser.", type: "choice" },
    { sentence: "¿De dónde ___ tú?", answer: "eres", explanation: "Origen → ser.", type: "write" },
    { sentence: "Ella ___ muy contenta con su nuevo trabajo.", answer: "está", explanation: "Estado emocional → estar.", type: "write" },
  ],
  condicionales: [
    { sentence: "Si ___ más temprano, no perderías el tren.", options: ["salieras", "sales", "saldrás", "salías"], answer: "salieras", explanation: "Condicional tipo 2: hipótesis sobre el presente.", type: "choice" },
    { sentence: "Si me ___ la verdad, no estaría enfadada.", answer: "hubieras dicho", explanation: "Condicional mixto: Si + pluscuamperfecto subjuntivo (pasado) + condicional (presente).", type: "write" },
    { sentence: "Si ___ a la fiesta, nos divertiríamos.", options: ["vinieras", "vienes", "vendrás", "venías"], answer: "vinieras", explanation: "Condicional tipo 2: Si + imperfecto de subjuntivo.", type: "choice" },
    { sentence: "Si ___ sol, iremos al parque.", answer: "hace", explanation: "Condicional tipo 1 (real): Si + presente indicativo.", type: "write" },
    { sentence: "Me ___ si pudiera.", options: ["ayudaría", "ayudo", "ayudaré", "ayudaba"], answer: "ayudaría", explanation: "Condicional tipo 2: resultado con condicional simple.", type: "choice" },
  ],
  "por-para": [
    { sentence: "Trabajo ___ vivir, no vivo ___ trabajar.", options: ["para, para", "por, por", "para, por", "por, para"], answer: "para, para", explanation: "'Para' en ambos casos indica finalidad/propósito.", type: "choice" },
    { sentence: "___ favor, dame un vaso de agua.", answer: "Por", explanation: "'Por favor' es una expresión fija.", type: "write" },
    { sentence: "Viajamos ___ toda Europa.", answer: "por", explanation: "'Por' indica movimiento a través de un lugar.", type: "write" },
    { sentence: "Lo compré ___ 20 euros.", options: ["por", "para"], answer: "por", explanation: "'Por' indica precio/intercambio.", type: "choice" },
    { sentence: "Estudio mucho ___ sacar buenas notas.", options: ["para", "por"], answer: "para", explanation: "'Para' indica objetivo/finalidad.", type: "choice" },
    { sentence: "Fue felicitado ___ su jefe.", options: ["por", "para"], answer: "por", explanation: "'Por' indica agente en voz pasiva.", type: "choice" },
  ],
  conectores: [
    { sentence: "No tengo hambre; ___, comeré algo ligero.", options: ["aun así", "por lo tanto", "además", "es decir"], answer: "aun así", explanation: "'Aun así' indica que, a pesar de lo anterior, se hace igualmente.", type: "choice" },
    { sentence: "El hotel era caro. ___, la ubicación era perfecta.", options: ["En cambio", "Por lo tanto", "Es decir", "Además"], answer: "En cambio", explanation: "'En cambio' introduce un contraste con aspecto positivo.", type: "choice" },
    { sentence: "Estoy cansado; ___, no puedo dormir.", answer: "sin embargo", explanation: "'Sin embargo' indica contraste/oposición.", type: "write" },
    { sentence: "Habla tres idiomas, ___ español, inglés y francés.", options: ["a saber", "sin embargo", "por lo tanto", "además"], answer: "a saber", explanation: "'A saber' introduce una enumeración/especificación.", type: "choice" },
    { sentence: "No solo es inteligente, ___ también simpática.", answer: "sino", explanation: "'No solo... sino también' es una correlación aditiva.", type: "write" },
  ],
  expresiones: [
    { sentence: "Estoy entre la ___ y la pared.", options: ["espada", "silla", "mesa", "puerta"], answer: "espada", explanation: "'Estar entre la espada y la pared' = estar en una situación difícil sin buenas opciones.", type: "choice" },
    { sentence: "Le echaron un ___ de mano.", options: ["cabo", "mano", "dedo", "brazo"], answer: "cabo", explanation: "'Echar un cable/cabo' = ayudar a alguien.", type: "choice" },
    { sentence: "No me vengas con ___.", options: ["cuentos", "historias", "libros", "novelas"], answer: "cuentos", explanation: "'No me vengas con cuentos' = no me digas mentiras/excusas.", type: "choice" },
    { sentence: "Más vale tarde que ___.", answer: "nunca", explanation: "'Más vale tarde que nunca' = es mejor hacer algo tarde que no hacerlo.", type: "write" },
    { sentence: "Tiene muchas ___.", options: ["tablas", "mesas", "sillas", "puertas"], answer: "tablas", explanation: "'Tener tablas' = tener mucha experiencia/soltura.", type: "choice" },
  ],
  preposiciones: [
    { sentence: "Me he acostumbrado ___ vivir aquí.", options: ["a", "de", "en", "con"], answer: "a", explanation: "'Acostumbrarse a' — siempre con 'a'.", type: "choice" },
    { sentence: "Se negó ___ ayudarme.", options: ["a", "de", "en", "por"], answer: "a", explanation: "'Negarse a' — siempre con 'a'.", type: "choice" },
    { sentence: "Consiste ___ tres partes.", options: ["en", "de", "a", "por"], answer: "en", explanation: "'Consistir en' — siempre con 'en'.", type: "choice" },
    { sentence: "Se enamoró ___ ella en la universidad.", answer: "de", explanation: "'Enamorarse de' — siempre con 'de'.", type: "write" },
    { sentence: "Contribuyó ___ mejorar la situación.", answer: "a", explanation: "'Contribuir a' — siempre con 'a'.", type: "write" },
    { sentence: "Renunció ___ su cargo.", options: ["a", "de", "en", "por"], answer: "a", explanation: "'Renunciar a' — siempre con 'a'.", type: "choice" },
  ],
  pasiva: [
    { sentence: "La carta fue ___ por María.", options: ["enviada", "enviar", "enviando", "envió"], answer: "enviada", explanation: "Pasiva con ser: ser + participio concordando con sujeto ('carta' = femenina).", type: "choice" },
    { sentence: "Se ___ tres idiomas en esta oficina.", options: ["hablan", "habla", "hablaron", "hablaba"], answer: "hablan", explanation: "Pasiva refleja: 'se' + verbo concordando con 'tres idiomas' (plural).", type: "choice" },
    { sentence: "En España se ___ mucho aceite de oliva.", answer: "consume", explanation: "Se impersonal/pasiva refleja con sujeto singular.", type: "write" },
    { sentence: "Las ventanas fueron ___ por el viento.", answer: "rotas", explanation: "Pasiva con ser: participio de 'romper' = 'roto/rotas' (concordancia femenino plural).", type: "write" },
  ],
  tildes: [
    { sentence: "¿Cuál es correcta? 'Yo ___ al médico'", options: ["fui", "fuí"], answer: "fui", explanation: "'Fui' es monosílaba y NO lleva tilde. Las palabras monosílabas no llevan tilde salvo excepciones (tilde diacrítica).", type: "choice" },
    { sentence: "Escribe correctamente: 'el pajaro'", answer: "el pájaro", explanation: "'Pájaro' es esdrújula → siempre lleva tilde.", type: "write" },
    { sentence: "Escribe correctamente: 'la pelicula'", answer: "la película", explanation: "'Película' es esdrújula → siempre lleva tilde.", type: "write" },
    { sentence: "¿Cuál es correcta? '___ lo dijo'", options: ["Él", "El"], answer: "Él", explanation: "'Él' (con tilde) = pronombre personal. 'El' (sin tilde) = artículo.", type: "choice" },
    { sentence: "¿Cuál es correcta? 'Quiero ___ vengas'", options: ["que", "qué"], answer: "que", explanation: "'Que' sin tilde = conjunción. 'Qué' con tilde = interrogativo/exclamativo.", type: "choice" },
    { sentence: "Escribe correctamente: 'la lampara'", answer: "la lámpara", explanation: "'Lámpara' es esdrújula → siempre lleva tilde.", type: "write" },
    { sentence: "Escribe correctamente: 'el examen'", answer: "el examen", explanation: "'Examen' es llana terminada en n → NO lleva tilde.", type: "write" },
    { sentence: "¿Cuál es correcta? '___ me gusta'", options: ["Sí", "Si"], answer: "Sí", explanation: "'Sí' (con tilde) = afirmación. 'Si' (sin tilde) = condicional.", type: "choice" },
  ],
};
