import type { Exercise } from "./exercises";

export const MORE_EXERCISES: Record<string, Exercise[]> = {
  subjuntivo: [
    { sentence: "Me molesta que ___ tanto ruido.", options: ["hagan", "hacen", "harán", "hicieron"], answer: "hagan", explanation: "'Molestar que' expresa emoción → subjuntivo.", type: "choice" },
    { sentence: "Tal vez ___ mañana.", options: ["venga", "viene", "vendrá", "vino"], answer: "venga", explanation: "'Tal vez' expresa posibilidad → subjuntivo.", type: "choice" },
    { sentence: "Le pedí que me ___ el libro.", options: ["devolviera", "devolvió", "devuelve", "devolverá"], answer: "devolviera", explanation: "'Pedir que' en pasado → imperfecto de subjuntivo.", type: "choice" },
    { sentence: "Es raro que no ___ todavía.", options: ["haya llegado", "ha llegado", "llegó", "llega"], answer: "haya llegado", explanation: "'Es raro que' → subjuntivo. Acción pasada → pretérito perfecto de subjuntivo.", type: "choice" },
    { sentence: "Habla como si ___ español nativo.", options: ["fuera", "es", "será", "fue"], answer: "fuera", explanation: "'Como si' siempre va con imperfecto de subjuntivo.", type: "choice" },
    { sentence: "No conozco a nadie que ___ tanto.", options: ["trabaje", "trabaja", "trabajará", "trabajó"], answer: "trabaje", explanation: "Antecedente negativo ('no conozco a nadie que') → subjuntivo.", type: "choice" },
    { sentence: "Te lo explico para que lo ___.", answer: "entiendas", explanation: "'Para que' → subjuntivo del verbo 'entender'.", type: "write", hint: "(verbo: entender)" },
    { sentence: "Quizás ___ razón.", answer: "tengas", explanation: "'Quizás' expresa duda → subjuntivo de 'tener'.", type: "write", hint: "(verbo: tener)" },
    { sentence: "No parece que ___ la verdad.", options: ["diga", "dice", "dirá", "dijo"], answer: "diga", explanation: "'No parecer que' expresa duda → subjuntivo.", type: "choice" },
    { sentence: "Prefiero que ___ tú.", options: ["conduzcas", "conduces", "conducirás", "condujiste"], answer: "conduzcas", explanation: "'Preferir que' → deseo sobre otra persona → subjuntivo.", type: "choice" },
    { sentence: "En caso de que ___, llámame.", options: ["necesites", "necesitas", "necesitarás", "necesitaste"], answer: "necesites", explanation: "'En caso de que' → siempre subjuntivo.", type: "choice" },
    { sentence: "Hasta que no ___ el contrato, no empezamos.", options: ["firme", "firma", "firmará", "firmó"], answer: "firme", explanation: "'Hasta que' + futuro → subjuntivo.", type: "choice" },
    { sentence: "Le dije que ___ temprano.", answer: "viniera", explanation: "'Decir que' (orden/petición) en pasado → imperfecto de subjuntivo de 'venir'.", type: "write", hint: "(verbo: venir)" },
    { sentence: "Ojalá ___ más tiempo libre.", answer: "tuviera", explanation: "'Ojalá' + deseo difícil/irreal → imperfecto de subjuntivo de 'tener'.", type: "write", hint: "(verbo: tener)" },
    { sentence: "No creo que lo ___ hecho a propósito.", options: ["haya", "ha", "había", "habrá"], answer: "haya", explanation: "'No creer que' → subjuntivo. Pasado → pretérito perfecto de subjuntivo.", type: "choice" },
    { sentence: "Espero que ___ un buen viaje.", answer: "tengas", explanation: "'Esperar que' → subjuntivo de 'tener'.", type: "write", hint: "(verbo: tener)" },
    { sentence: "Aunque ___ cansado, iré a la fiesta.", options: ["esté", "estoy", "estaré", "estuve"], answer: "esté", explanation: "'Aunque' + situación hipotética/indiferente → subjuntivo.", type: "choice" },
    { sentence: "Siempre que ___ buen tiempo, salimos.", options: ["haga", "hace", "hará", "hizo"], answer: "haga", explanation: "'Siempre que' con sentido condicional → subjuntivo.", type: "choice" },
    { sentence: "No es que no ___, es que no puedo.", options: ["quiera", "quiero", "querré", "quise"], answer: "quiera", explanation: "'No es que' niega → subjuntivo.", type: "choice" },
    { sentence: "Me sorprende que ___ tan joven.", options: ["sea", "es", "será", "fue"], answer: "sea", explanation: "'Sorprender que' → emoción → subjuntivo.", type: "choice" },
  ],
  pasados: [
    { sentence: "___ las tres de la tarde cuando ___ a llover.", options: ["Eran, empezó", "Fueron, empezaba", "Eran, empezaba", "Fueron, empezó"], answer: "Eran, empezó", explanation: "Hora (imperfecto) + evento puntual (indefinido).", type: "choice" },
    { sentence: "Cada verano ___ a la playa con mi familia.", options: ["íbamos", "fuimos", "hemos ido", "iremos"], answer: "íbamos", explanation: "'Cada verano' = hábito repetido → imperfecto.", type: "choice" },
    { sentence: "Aquella noche ___ mucho y no ___ salir.", options: ["llovía, pudimos", "llovió, podíamos", "llovía, podíamos", "llovió, pudimos"], answer: "llovía, pudimos", explanation: "Contexto climático (imperfecto) + resultado puntual (indefinido).", type: "choice" },
    { sentence: "La primera vez que ___ sushi, no me ___.", options: ["probé, gustó", "probaba, gustaba", "probé, gustaba", "probaba, gustó"], answer: "probé, gustó", explanation: "'La primera vez' = evento único → ambos en indefinido.", type: "choice" },
    { sentence: "Antes ___ fumar, pero lo dejé hace un año.", options: ["solía", "solí", "he solido", "suelo"], answer: "solía", explanation: "'Antes' + hábito pasado → 'solía' (imperfecto).", type: "choice" },
    { sentence: "De repente, alguien ___ a la puerta.", options: ["llamó", "llamaba", "ha llamado", "llamará"], answer: "llamó", explanation: "'De repente' indica acción súbita → indefinido.", type: "choice" },
    { sentence: "Mientras ___ por el parque, ___ a un viejo amigo.", answer: "paseaba, encontré", explanation: "Acción en curso (imperfecto) + interrupción (indefinido).", type: "write", hint: "(verbos: pasear, encontrar)" },
    { sentence: "El año pasado ___ de trabajo tres veces.", answer: "cambié", explanation: "Acción completada con número específico → indefinido de 'cambiar'.", type: "write", hint: "(verbo: cambiar)" },
    { sentence: "De niño me ___ mucho los dibujos animados.", options: ["gustaban", "gustaron", "han gustado", "gustarán"], answer: "gustaban", explanation: "'De niño' = época pasada habitual → imperfecto.", type: "choice" },
    { sentence: "Aquel día ___ una decisión importante.", options: ["tomé", "tomaba", "he tomado", "tomaré"], answer: "tomé", explanation: "'Aquel día' = momento específico completado → indefinido.", type: "choice" },
    { sentence: "Cuando ___ joven, ___ mucho al fútbol.", options: ["era, jugaba", "fui, jugué", "era, jugué", "fui, jugaba"], answer: "era, jugaba", explanation: "Época (imperfecto) + hábito dentro de esa época (imperfecto).", type: "choice" },
    { sentence: "Ayer ___ todo el día en casa porque ___.", options: ["estuve, llovía", "estaba, llovió", "estuve, llovió", "estaba, llovía"], answer: "estuve, llovía", explanation: "Acción con duración definida (indefinido) + clima de fondo (imperfecto).", type: "choice" },
    { sentence: "No ___ qué decir cuando me ___ la noticia.", answer: "sabía, dieron", explanation: "Estado mental (imperfecto) + acción puntual (indefinido).", type: "write", hint: "(verbos: saber, dar)" },
    { sentence: "La película ___ dos horas.", options: ["duró", "duraba", "ha durado", "durará"], answer: "duró", explanation: "Duración definida y completada → indefinido.", type: "choice" },
    { sentence: "En aquella época no ___ móviles.", options: ["había", "hubo", "ha habido", "habrá"], answer: "había", explanation: "Descripción de una época → imperfecto.", type: "choice" },
    { sentence: "Mi abuelo siempre nos ___ historias antes de dormir.", answer: "contaba", explanation: "'Siempre' + acción repetida en el pasado → imperfecto de 'contar'.", type: "write", hint: "(verbo: contar)" },
    { sentence: "Cuando ___ al colegio, ___ mucho.", options: ["iba, leía", "fui, leí", "iba, leí", "fui, leía"], answer: "iba, leía", explanation: "Época + hábito → ambos imperfecto.", type: "choice" },
    { sentence: "Ayer no ___ ir a trabajar porque ___ enfermo.", options: ["pude, estaba", "podía, estuve", "pude, estuve", "podía, estaba"], answer: "pude, estaba", explanation: "Resultado puntual (indefinido) + estado como causa (imperfecto).", type: "choice" },
    { sentence: "En 2020 ___ la pandemia.", options: ["empezó", "empezaba", "ha empezado", "empezará"], answer: "empezó", explanation: "Hecho histórico con fecha → indefinido.", type: "choice" },
    { sentence: "Cuando ___ joven, mi madre ___ muy guapa.", answer: "era, era", explanation: "Dos descripciones de una época pasada → ambas imperfecto.", type: "write", hint: "(verbo: ser)" },
  ],
  "estaba-estuvo": [
    { sentence: "La comida ___ buenísima.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Valoración de algo ya terminado (la comida que comiste) → indefinido.", type: "choice" },
    { sentence: "___ nevando cuando salimos.", options: ["Estaba", "Estuvo"], answer: "Estaba", explanation: "Acción en curso como contexto → imperfecto.", type: "choice" },
    { sentence: "La exposición ___ abierta solo un mes.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Duración limitada y completada → indefinido.", type: "choice" },
    { sentence: "Cuando llegué a la oficina, nadie ___ trabajando.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Estado encontrado al llegar → imperfecto.", type: "choice" },
    { sentence: "Ayer ___ todo el día estudiando.", options: ["estuve", "estaba"], answer: "estuve", explanation: "'Todo el día' = duración completa → indefinido.", type: "choice" },
    { sentence: "La casa ___ vacía porque todos se fueron.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Estado resultante/descripción → imperfecto.", type: "choice" },
    { sentence: "El hotel ___ bastante bien para el precio.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Valoración de una experiencia terminada → indefinido.", type: "choice" },
    { sentence: "Mi madre ___ preocupada porque no llamé.", answer: "estaba", explanation: "Estado emocional como contexto → imperfecto.", type: "write" },
    { sentence: "La conferencia ___ muy interesante.", answer: "estuvo", explanation: "Valoración de evento terminado → indefinido.", type: "write" },
    { sentence: "___ haciendo la cena cuando sonó el timbre.", answer: "Estaba", explanation: "Acción en curso interrumpida → imperfecto.", type: "write" },
    { sentence: "Juan ___ viviendo en Londres dos años.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Período cerrado ('dos años') → indefinido.", type: "choice" },
    { sentence: "El cielo ___ nublado toda la semana.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "'Toda la semana' = duración completa y cerrada → indefinido.", type: "choice" },
    { sentence: "No sé por qué ___ tan triste ayer.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Pregunta sobre un estado en un momento específico → imperfecto.", type: "choice" },
    { sentence: "La calle ___ mojada por la lluvia.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Estado resultante/descripción visual → imperfecto.", type: "choice" },
    { sentence: "El examen ___ difícil.", answer: "estuvo", explanation: "Valoración de algo ya terminado → indefinido.", type: "write" },
    { sentence: "Antes siempre ___ contenta.", answer: "estaba", explanation: "Estado habitual en el pasado ('antes siempre') → imperfecto.", type: "write" },
    { sentence: "El partido ___ muy emocionante.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Valoración global de un evento completado → indefinido.", type: "choice" },
    { sentence: "___ lloviendo tres horas seguidas.", options: ["Estuvo", "Estaba"], answer: "Estuvo", explanation: "Duración específica completada → indefinido.", type: "choice" },
    { sentence: "Cuando la llamé, ___ durmiendo.", options: ["estaba", "estuvo"], answer: "estaba", explanation: "Acción en curso en el momento de llamar → imperfecto.", type: "choice" },
    { sentence: "El viaje ___ largo pero mereció la pena.", options: ["estuvo", "estaba"], answer: "estuvo", explanation: "Valoración de experiencia terminada → indefinido.", type: "choice" },
  ],
  "ser-estar": [
    { sentence: "La ventana ___ rota.", options: ["está", "es"], answer: "está", explanation: "Resultado de una acción (alguien la rompió) → estar.", type: "choice" },
    { sentence: "Mi hermana ___ muy inteligente.", options: ["es", "está"], answer: "es", explanation: "Característica permanente/inherente → ser.", type: "choice" },
    { sentence: "El café ___ frío.", options: ["está", "es"], answer: "está", explanation: "Estado temporal (se enfrió) → estar.", type: "choice" },
    { sentence: "Esta camisa ___ de algodón.", options: ["es", "está"], answer: "es", explanation: "Material → ser.", type: "choice" },
    { sentence: "___ importante estudiar todos los días.", options: ["Es", "Está"], answer: "Es", explanation: "Juicio/valoración impersonal → ser.", type: "choice" },
    { sentence: "La biblioteca ___ al lado del parque.", options: ["está", "es"], answer: "está", explanation: "Ubicación de objetos/edificios → estar.", type: "choice" },
    { sentence: "Estos zapatos ___ muy caros.", options: ["son", "están"], answer: "son", explanation: "Precio como característica → ser.", type: "choice" },
    { sentence: "Hoy ___ muy guapa.", answer: "estás", explanation: "'Estar guapa' = se ve guapa hoy (cambio/apreciación temporal).", type: "write" },
    { sentence: "Mi padre ___ de Madrid.", answer: "es", explanation: "Origen → ser.", type: "write" },
    { sentence: "La leche ___ caducada.", answer: "está", explanation: "Estado resultante (se caducó) → estar.", type: "write" },
    { sentence: "La boda ___ en la iglesia del pueblo.", options: ["es", "está"], answer: "es", explanation: "Ubicación de eventos → ser.", type: "choice" },
    { sentence: "Pedro ___ abogado, pero ahora ___ en paro.", options: ["es, está", "está, es", "es, es", "está, está"], answer: "es, está", explanation: "Profesión (ser) + situación temporal (estar).", type: "choice" },
    { sentence: "La puerta ___ de madera y ___ pintada de azul.", options: ["es, está", "está, es", "es, es", "está, está"], answer: "es, está", explanation: "Material (ser) + estado resultado de pintar (estar).", type: "choice" },
    { sentence: "¿Qué hora ___?", answer: "es", explanation: "Preguntar la hora → ser.", type: "write" },
    { sentence: "Ella ___ muy simpática pero hoy ___ de mal humor.", options: ["es, está", "está, es", "es, es", "está, está"], answer: "es, está", explanation: "Personalidad (ser) + estado temporal (estar).", type: "choice" },
    { sentence: "La sopa ya ___ lista.", answer: "está", explanation: "'Estar listo/a' = preparado/a.", type: "write" },
    { sentence: "No ___ justo que trabaje más que los demás.", options: ["es", "está"], answer: "es", explanation: "Valoración impersonal → ser.", type: "choice" },
    { sentence: "Las manzanas ___ verdes.", options: ["están", "son"], answer: "están", explanation: "Estado de madurez (pueden cambiar) → estar.", type: "choice" },
    { sentence: "Ella ___ de vacaciones.", options: ["está", "es"], answer: "está", explanation: "Situación temporal → estar.", type: "choice" },
    { sentence: "El concierto ___ a las nueve.", options: ["es", "está"], answer: "es", explanation: "Hora de eventos → ser.", type: "choice" },
  ],
  condicionales: [
    { sentence: "Si ___ rico, compraría una isla.", options: ["fuera", "soy", "seré", "era"], answer: "fuera", explanation: "Condicional tipo 2: hipótesis irreal sobre el presente.", type: "choice" },
    { sentence: "Si llueve, ___ el paraguas.", options: ["cogeré", "cogería", "cogiera", "cogía"], answer: "cogeré", explanation: "Condicional tipo 1: situación real/posible → futuro.", type: "choice" },
    { sentence: "Si ___ estudiar más, habría aprobado.", options: ["hubiera podido", "pude", "puedo", "podría"], answer: "hubiera podido", explanation: "Condicional tipo 3: pasado irreal.", type: "choice" },
    { sentence: "Si ___ que era tu cumpleaños, te habría llamado.", answer: "hubiera sabido", explanation: "Tipo 3: Si + pluscuamperfecto de subjuntivo.", type: "write", hint: "(verbo: saber)" },
    { sentence: "Iría contigo si no ___ tanto trabajo.", options: ["tuviera", "tengo", "tendré", "tenía"], answer: "tuviera", explanation: "Tipo 2: hipótesis sobre el presente.", type: "choice" },
    { sentence: "Si ___ más joven, aprendería a tocar el piano.", options: ["fuera", "soy", "seré", "era"], answer: "fuera", explanation: "Tipo 2: deseo irreal sobre el presente.", type: "choice" },
    { sentence: "Si pudieras viajar a cualquier país, ¿adónde ___?", answer: "irías", explanation: "Resultado del condicional tipo 2 → condicional simple de 'ir'.", type: "write", hint: "(verbo: ir)" },
    { sentence: "No habría pasado nada si ___ con cuidado.", options: ["hubieras conducido", "conduces", "conducías", "conducirás"], answer: "hubieras conducido", explanation: "Tipo 3: consecuencia pasada irreal.", type: "choice" },
    { sentence: "Si me ___ la lotería, dejaría de trabajar.", options: ["tocara", "toca", "tocará", "tocó"], answer: "tocara", explanation: "Tipo 2: hipótesis improbable.", type: "choice" },
    { sentence: "Si no ___ tan tarde, podríamos ir al cine.", options: ["fuera", "es", "será", "era"], answer: "fuera", explanation: "Tipo 2: condición hipotética sobre el presente.", type: "choice" },
    { sentence: "Si ___ buena nota, mis padres me regalarán un viaje.", answer: "saco", explanation: "Tipo 1 (real): Si + presente indicativo.", type: "write", hint: "(verbo: sacar)" },
    { sentence: "Te ___ si pudiera.", options: ["ayudaría", "ayudo", "ayudaré", "ayudé"], answer: "ayudaría", explanation: "Resultado del tipo 2 → condicional simple.", type: "choice" },
    { sentence: "Si ___ mejor el español, entendería las películas.", options: ["hablara", "hablo", "hablaré", "hablaba"], answer: "hablara", explanation: "Tipo 2: hipótesis sobre habilidad presente.", type: "choice" },
    { sentence: "Si no ___ tanto tráfico, habríamos llegado a tiempo.", answer: "hubiera habido", explanation: "Tipo 3: condición pasada irreal de 'haber'.", type: "write", hint: "(verbo: haber)" },
    { sentence: "¿Qué ___ si pudieras cambiar algo de tu vida?", answer: "cambiarías", explanation: "Resultado tipo 2 → condicional de 'cambiar'.", type: "write", hint: "(verbo: cambiar)" },
    { sentence: "Si ___ tiempo, ven a verme.", options: ["tienes", "tuvieras", "tendrás", "tenías"], answer: "tienes", explanation: "Tipo 1: condición real posible → presente indicativo.", type: "choice" },
    { sentence: "Si yo ___ presidente, cambiaría muchas cosas.", options: ["fuera", "soy", "seré", "era"], answer: "fuera", explanation: "Tipo 2: hipótesis irreal.", type: "choice" },
    { sentence: "Nos ___ ido de vacaciones si no ___ la pandemia.", options: ["habríamos, hubiera sido", "habríamos, fue", "iríamos, hubiera sido", "iríamos, fue"], answer: "habríamos, hubiera sido", explanation: "Tipo 3: condicional compuesto + pluscuamperfecto subjuntivo.", type: "choice" },
    { sentence: "Si ___ que era peligroso, no iría.", options: ["supiera", "sé", "sabré", "sabía"], answer: "supiera", explanation: "Tipo 2: Si + imperfecto de subjuntivo.", type: "choice" },
    { sentence: "Si me lo ___ , te habría ayudado.", answer: "hubieras pedido", explanation: "Tipo 3: Si + pluscuamperfecto subjuntivo de 'pedir'.", type: "write", hint: "(verbo: pedir)" },
  ],
};
